[package]
name = "rocket-example"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
rocket = "0.5.1"
serde_json = "1.0.140"

[dependencies.line_bot_sdk_rust]
git = "https://github.com/Kayxue/LineBotSdkRust.git"
branch = "master"
features = ["rocket_support"]
