[package]
name = "actix-example"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
dotenv = "0.15.0"
serde_json = "1.0.140"


[dependencies.line_bot_sdk_rust]
git = "https://github.com/Kayxue/LineBotSdkRust.git"
branch = "master"
features = ["actix_support"]
